---
version: '3'

services:
  dbt:
    image: entechlog/dbt${DBT_VERSION_TAG}
    container_name: dbt
    build: ./docker/dbt/
    env_file:
      - ./docker/dbt/.env
    command: 
      - bash 
      - -c 
      - |
        echo "Launching dbt"
        #
        sleep infinity
    restart: unless-stopped
    volumes:
      - ./.dbt/profiles.yml:/secure/profile/profiles.yml
      - ./dbt:/data/dbt
    ports:
      - "8085:8080"
    environment:
      - TZ=Etc/GMT

  postgres:
    image: postgres${POSTGRES_VERSION_TAG}
    container_name: airflow-postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    logging:
        options:
            max-size: 10m
            max-file: "3"

  airflow-webserver:
      image: puckel/docker-airflow${AIRFLOW_VERSION_TAG}
      container_name: airflow-webserver
      restart: always
      depends_on:
          - postgres
      environment:
          - LOAD_EX=n
          - EXECUTOR=Local
      logging:
          options:
              max-size: 10m
              max-file: "3"
      volumes:
        - ./dags:/usr/local/airflow/dags
        - ./docker/airflow/requirements.txt:/requirements.txt
        - //var/run/docker.sock:/var/run/docker.sock:rw
      ports:
          - "8080:8080"
      command: webserver
      healthcheck:
          test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
          interval: 30s
          timeout: 30s
          retries: 3