---
version: "3"

services:
  postgres:
    image: postgres${POSTGRES_VERSION_TAG}
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./docker/postgres/data.sql:/docker-entrypoint-initdb.d/2-data.sql

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"

