version: 2

sources:
  - name: raw
    tables:
      - name: sakila_actor
      - name: sakila_address
      - name: sakila_category
      - name: sakila_city
      - name: sakila_country
      - name: sakila_customer
      - name: sakila_film
      - name: sakila_film_actor
      - name: sakila_film_category
      - name: sakila_film_text
      - name: sakila_inventory
      - name: sakila_language
      - name: sakila_payment
      - name: sakila_rental
      - name: sakila_staff
      - name: sakila_store

  - name: reference
    tables:
      - name: country

models:
  - name: customer
    description: This table contains information about customers who rented the movie 
    columns:
      - name: customer_id
        description: This is a unique identifier for customer
        tests:
          - unique
          - not_null
          - dbt_expectations.expect_column_values_to_be_unique
      - name: customer_first_name
        tests:
          - not_null
      - name: customer_last_name
      - name: customer_email
      - name: customer_active
      - name: customer_created
      - name: customer_address
      - name: customer_district
      - name: customer_postal_code
      - name: customer_phone_number
      - name: customer_city
      - name: customer_country
      - name: last_update
